# Generated by Django 5.0.2 on 2024-02-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='audio_file',
        ),
    ]
